name: pos_app
description: A Point of Sale Flutter application using GetX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6  # For GetX state management
  fl_chart: ^0.65.0  # For charts in dashboard
  shared_preferences: ^2.2.2  # For local storage (login session)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/